package models

const (
	MODEL_MATERIAL_TYPE_VEGETABLE_FRUIT = 1
	MODEL_MATERIAL_TYPE_MEAT_EGGS = 2
	MODEL_MATERIAL_TYPE_RICE_OIL = 3
	MODEL_MATERIAL_TYPE_CONDIMENT = 4
	MODEL_MATERIAL_TYPE_OTHER = 5
)

